spring:
  application:
    name: "config-server"
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/herman-87/config-fastrelay.git"
          default-label: "main"
          search-paths:
            - "config"
          clone-on-start: true
  profiles:
    active: "git"

server:
  port: "${SERVER_PORT:8088}"