spring:
  application:
    name: "${SPRING_APPLICATION_NAME:business}"
  datasource:
    url: "${DB_URL}"
  kafka:
    bootstrap-servers: kafka:29092
    topic:
      user-created: "user-created"
      subscription-created: "subscription-created"
      subscription-expired: "subscription-expired"
      business-created: "business-created"
    consumer-groups:
      user-created-group-id: "business-user-created"
      subscription-created-group-id: "business-subscription-created"
      subscription-expired-group-id: "business-subscription-expired"
