spring:
  application:
    name: "${SPRING_APPLICATION_NAME:image}"

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    url: "${DB_URL}"

app:
  upload:
    max-file-size: 5242880

minio:
  endpoint: "${MINIO_ENDPOINT}"
  access-key: "${MINIO_ACCESS_KEY}"
  secret-key: "${MINIO_SECRET_KEY}"
  default-bucket-name: images
