spring:
  application:
    name: "${SPRING_APPLICATION_NAME:likes}"
  datasource:
    url: "${DB_URL}"
  cache:
    type: redis
  data:
    redis:
      host: "${REDIS_HOST:redis}"
      port: "${REDIS_PORT:6379}"
  cloud:
    stream:
      bindings:
        likeCreated-out-0:
          destination: "${KAFKA_TOPIC_LIKE_CREATED:like-created}"
        likeRemoved-out-0:
          destination: "${KAFKA_TOPIC_LIKE_REMOVED:like-removed}"
      kafka:
        binder:
          configuration:
            schema.registry.url: "${SCHEMA_REGISTRY_URL:http://schema-registry:8081}"
            value.serializer: "io.confluent.kafka.serializers.KafkaAvroSerializer"
        bindings:
          likeCreated-out-0:
            producer:
              useNativeEncoding: true
          likeRemoved-out-0:
            producer:
              useNativeEncoding: true
