spring:
  application:
    name: "${SPRING_APPLICATION_NAME:notifications}"
  datasource:
    url: "${DB_URL}"
  cloud:
    function:
      definition: orderRequestCreatedConsumer;userCreatedConsumer;businessCreatedConsumer;articleCreatedConsumer;promotionCreatedConsumer;subscriptionCreatedConsumer;productPublishedConsumer;promotionStartedConsumer;promotionClosedConsumer;orderPaidConsumer;orderAcceptedConsumer;orderDeliveredConsumer;orderDeliveryAcceptedConsumer
    stream:
      bindings:
        orderRequestCreatedConsumer-in-0:
          destination: "${KAFKA_TOPIC_ORDER_REQUEST_CREATED:order-request-created}"
          group: "${KAFKA_GROUP_ID:notifications-service}"
          content-type: "application/json"
        userCreatedConsumer-in-0:
          destination: "${KAFKA_TOPIC_USER_CREATED:user-created}"
          group: "${KAFKA_GROUP_ID:notifications-service}"
          content-type: "application/json"
        businessCreatedConsumer-in-0:
          destination: "${KAFKA_TOPIC_BUSINESS_CREATED:business-created}"
          group: "${KAFKA_GROUP_ID:notifications-service}"
          content-type: "application/json"
        articleCreatedConsumer-in-0:
          destination: "${KAFKA_TOPIC_ARTICLE_CREATED:article-created}"
          group: "${KAFKA_GROUP_ID:notifications-service}"
          content-type: "application/json"
        promotionCreatedConsumer-in-0:
          destination: "${KAFKA_TOPIC_PROMOTION_CREATED:promotion-created}"
          group: "${KAFKA_GROUP_ID:notifications-service}"
          content-type: "application/json"
        subscriptionCreatedConsumer-in-0:
          destination: "${KAFKA_TOPIC_SUBSCRIPTION_CREATED:subscription-created}"
          group: "${KAFKA_GROUP_ID:notifications-service}"
          content-type: "application/json"
        productPublishedConsumer-in-0:
          destination: "${KAFKA_TOPIC_PRODUCT_PUBLISHED:product-published}"
          group: "${KAFKA_GROUP_ID:notifications-service}"
          content-type: "application/json"
        promotionStartedConsumer-in-0:
          destination: "${KAFKA_TOPIC_PROMOTION_STARTED:promotion-started}"
          group: "${KAFKA_GROUP_ID:notifications-service}"
          content-type: "application/json"
        promotionClosedConsumer-in-0:
          destination: "${KAFKA_TOPIC_PROMOTION_CLOSED:promotion-closed}"
          group: "${KAFKA_GROUP_ID:notifications-service}"
          content-type: "application/json"
        orderPaidConsumer-in-0:
          destination: "${KAFKA_TOPIC_ORDER_PAID:order-paid}"
          group: "${KAFKA_GROUP_ID:notifications-service}"
          content-type: "application/json"
        orderAcceptedConsumer-in-0:
          destination: "${KAFKA_TOPIC_ORDER_ACCEPTED:order-accepted}"
          group: "${KAFKA_GROUP_ID:notifications-service}"
          content-type: "application/json"
        orderDeliveredConsumer-in-0:
          destination: "${KAFKA_TOPIC_ORDER_DELIVERED:order-delivered}"
          group: "${KAFKA_GROUP_ID:notifications-service}"
          content-type: "application/json"
        orderDeliveryAcceptedConsumer-in-0:
          destination: "${KAFKA_TOPIC_ORDER_DELIVERY_ACCEPTED:order-delivery-accepted}"
          group: "${KAFKA_GROUP_ID:notifications-service}"
          content-type: "application/json"
      kafka:
        bindings:
          orderRequestCreatedConsumer-in-0:
            consumer:
              start-offset: earliest
              enable-dlq: true
              dlq-name: "${KAFKA_TOPIC_ORDER_REQUEST_CREATED:order-request-created}.dlq"
          userCreatedConsumer-in-0:
            consumer:
              start-offset: earliest
              enable-dlq: true
              dlq-name: "${KAFKA_TOPIC_USER_CREATED:user-created}.dlq"
          businessCreatedConsumer-in-0:
            consumer:
              start-offset: earliest
              enable-dlq: true
              dlq-name: "${KAFKA_TOPIC_BUSINESS_CREATED:business-created}.dlq"
          articleCreatedConsumer-in-0:
            consumer:
              start-offset: earliest
              enable-dlq: true
              dlq-name: "${KAFKA_TOPIC_ARTICLE_CREATED:article-created}.dlq"
          promotionCreatedConsumer-in-0:
            consumer:
              start-offset: earliest
              enable-dlq: true
              dlq-name: "${KAFKA_TOPIC_PROMOTION_CREATED:promotion-created}.dlq"
          subscriptionCreatedConsumer-in-0:
            consumer:
              start-offset: earliest
              enable-dlq: true
              dlq-name: "${KAFKA_TOPIC_SUBSCRIPTION_CREATED:subscription-created}.dlq"
          productPublishedConsumer-in-0:
            consumer:
              start-offset: earliest
              enable-dlq: true
              dlq-name: "${KAFKA_TOPIC_PRODUCT_PUBLISHED:product-published}.dlq"
          promotionStartedConsumer-in-0:
            consumer:
              start-offset: earliest
              enable-dlq: true
              dlq-name: "${KAFKA_TOPIC_PROMOTION_STARTED:promotion-started}.dlq"
          promotionClosedConsumer-in-0:
            consumer:
              start-offset: earliest
              enable-dlq: true
              dlq-name: "${KAFKA_TOPIC_PROMOTION_CLOSED:promotion-closed}.dlq"
          orderPaidConsumer-in-0:
            consumer:
              start-offset: earliest
              enable-dlq: true
              dlq-name: "${KAFKA_TOPIC_ORDER_PAID:order-paid}.dlq"
          orderAcceptedConsumer-in-0:
            consumer:
              start-offset: earliest
              enable-dlq: true
              dlq-name: "${KAFKA_TOPIC_ORDER_ACCEPTED:order-accepted}.dlq"
          orderDeliveredConsumer-in-0:
            consumer:
              start-offset: earliest
              enable-dlq: true
              dlq-name: "${KAFKA_TOPIC_ORDER_DELIVERED:order-delivered}.dlq"
          orderDeliveryAcceptedConsumer-in-0:
            consumer:
              start-offset: earliest
              enable-dlq: true
              dlq-name: "${KAFKA_TOPIC_ORDER_DELIVERY_ACCEPTED:order-delivery-accepted}.dlq"

notifications:
  email:
    from: "${NOTIFICATIONS_EMAIL_FROM:fastrelays@gmail.com}"
    max-retries: "${NOTIFICATIONS_EMAIL_MAX_RETRIES:3}"
  scheduler:
    interval: "${NOTIFICATIONS_SCHEDULER_INTERVAL:30000}"
    expire-cron: "${NOTIFICATIONS_SCHEDULER_EXPIRE_CRON:0 0 0 * * *}"
    expiry-days: "${NOTIFICATIONS_SCHEDULER_EXPIRY_DAYS:30}"

mailer:
  base-url: "${MAILER_BASE_URL:http://mailer:3000}"

server:
  port: "${SERVER_PORT:8095}"
