spring:
  application:
    name: "${SPRING_APPLICATION_NAME:order}"
  cache:
    type: redis
  data:
    redis:
      host: "${REDIS_HOST:redis}"
      port: "${REDIS_PORT:6379}"
  datasource:
    url: "${DB_URL}"
  cloud:
    function:
      definition: userCreatedConsumer;transferRequestCreatedConsumer
    stream:
      bindings:
        userCreatedConsumer-in-0:
          destination: "${KAFKA_TOPIC_USER_CREATED:user-created}"
          group: "${KAFKA_GROUP_ID:order-service}"
          content-type: "application/json"
        transferRequestCreatedConsumer-in-0:
          destination: "${KAFKA_TOPIC_TRANSFER_CREATED:transfer-request-created}"
          group: "${KAFKA_GROUP_ID:order-service}"
          content-type: "application/json"
        orderRequestCreated-out-0:
          destination: "${KAFKA_TOPIC_ORDER_REQUEST_CREATED:order-request-created}"
          content-type: "application/json"
      kafka:
        bindings:
          userCreatedConsumer-in-0:
            consumer:
              start-offset: earliest
              enable-dlq: true
              dlq-name: "${KAFKA_TOPIC_USER_CREATED:user-created}.dlq"
          transferRequestCreatedConsumer-in-0:
            consumer:
              start-offset: earliest
              enable-dlq: true
              dlq-name: "${KAFKA_TOPIC_TRANSFER_CREATED:transfer-request-created}.dlq"
