spring:
  application:
    name: "${SPRING_APPLICATION_NAME:order}"
  datasource:
    url: "${DB_URL}"
  kafka:
    bootstrap-servers: kafka:29092
    producer:
      key-serializer: "org.apache.kafka.common.serialization.StringSerializer"
      value-serializer: "org.springframework.kafka.support.serializer.JsonSerializer"
    consumer:
      group-id: "order-service"
    topic:
      user-created: "user-created"
      order-request-created: "order-request-created"
      transfer-request-created: "transfer-request-created"
