spring:
  application:
    batch:
      jdbc:
        initialize-schema: "${SPRING_BATCH_JDBC_INITIALIZE_SCHEMA:always}"
    name: "${SPRING_APPLICATION_NAME:payment}"
  datasource:
    url: "${DB_URL}"
  kafka:
    producer:
      key-serializer: "org.apache.kafka.common.serialization.StringSerializer"
      value-serializer: "org.springframework.kafka.support.serializer.JsonSerializer"
    consumer:
      group-id: "${KAFKA_GROUP_ID:payment-service}"
    topic:
      user-created: "${KAFKA_TOPIC_USER_CREATED:user-created}"
      transfer-request-created: "${KAFKA_TOPIC_TRANSFER_CREATED:transfer-request-created}"

app:
  webhook:
    base-url: "${APP_WEBHOOK_BASE_URL:https://fastrelays/payment/alert}"
  external:
    service:
      monetbil:
        enabled: "${PAYMENT_EXTERNAL_SERVICE_MONETBIL_ENABLED:true}"
        url: "${PAYMENT_EXTERNAL_SERVICE_MONETBIL_URL:https://api.monetbil.com}"
        service-key: "${PAYMENT_EXTERNAL_SERVICE_MONETBIL_KEY}"
      pawapay:
        enabled: "${PAYMENT_EXTERNAL_SERVICE_PAWAPAY_ENABLED:true}"
        bearer-token: "${PAYMENT_PAWAPAY_BEARER_TOKEN:}"
        url: "${PAYMENT_EXTERNAL_SERVICE_PAWAPAY_URL}"
        token: "${PAYMENT_EXTERNAL_SERVICE_PAWAPAY_TOKEN}"
