spring:
  application:
    name: "${SPRING_APPLICATION_NAME:payment}"
  batch:
    jdbc:
      initialize-schema: "${SPRING_BATCH_JDBC_INITIALIZE_SCHEMA:always}"
  datasource:
    url: "${DB_URL}"
  kafka:
    bootstrap-servers: kafka:29092
    producer:
      key-serializer: "org.apache.kafka.common.serialization.StringSerializer"
      value-serializer: "org.springframework.kafka.support.serializer.JsonSerializer"
    consumer:
      group-id: "${KAFKA_GROUP_ID:payment-service}"
    topic:
      user-created: "${KAFKA_TOPIC_USER_CREATED:user-created}"
      business-created: "${KAFKA_TOPIC_BUSINESS_CREATED:business-created}"
      transfer-request-created: "${KAFKA_TOPIC_TRANSFER_CREATED:transfer-request-created}"

app:
  account:
    platform-number: "${APP_PLATFORM_ACCOUNT_NUMBER:671952927}"
  webhook:
    base-url: "${APP_WEBHOOK_BASE_URL:https://fastrelays/payment/monetbil/notify}"
  external:
    service:
      monetbil:
        enabled: "${PAYMENT_EXTERNAL_SERVICE_MONETBIL_ENABLED:true}"
        url: "${PAYMENT_EXTERNAL_SERVICE_MONETBIL_URL:https://api.monetbil.com}"
        service-key: "${PAYMENT_EXTERNAL_SERVICE_MONETBIL_KEY}"
        service-secret: "${PAYMENT_EXTERNAL_SERVICE_MONETBIL_SECRET}"
      pawapay:
        enabled: "${PAYMENT_EXTERNAL_SERVICE_PAWAPAY_ENABLED:true}"
        bearer-token: "${PAYMENT_PAWAPAY_BEARER_TOKEN:}"
        url: "${PAYMENT_EXTERNAL_SERVICE_PAWAPAY_URL}"
        token: "${PAYMENT_EXTERNAL_SERVICE_PAWAPAY_TOKEN}"
