spring:
  application:
    name: "${SPRING_APPLICATION_NAME:product}"
  cache:
    type: redis
  data:
    redis:
      host: "${REDIS_HOST:redis}"
      port: "${REDIS_PORT:6379}"
  datasource:
    url: "${DB_URL}"
  cloud:
    stream:
      bindings:
        articleCreated-out-0:
          destination: "${KAFKA_TOPIC_ARTICLE_CREATED:article-created}"
          content-type: "application/json"
        promotionCreated-out-0:
          destination: "${KAFKA_TOPIC_PROMOTION_CREATED:promotion-created}"
          content-type: "application/json"

application:
  promotion:
    batch:
      cron: "0 */5 * * * *"
