spring:
  application:
    name: "${SPRING_APPLICATION_NAME:product}"
  cache:
    type: redis
  data:
    redis:
      host: "${REDIS_HOST:redis}"
      port: "${REDIS_PORT:6379}"
  datasource:
    url: "${DB_URL}"
  cloud:
    stream:
      bindings:
        articleCreated-out-0:
          destination: "${KAFKA_TOPIC_ARTICLE_CREATED:article-created}"
        promotionCreated-out-0:
          destination: "${KAFKA_TOPIC_PROMOTION_CREATED:promotion-created}"
        productPublished-out-0:
          destination: "${KAFKA_TOPIC_PRODUCT_PUBLISHED:product-published}"
        productUnpublished-out-0:
          destination: "${KAFKA_TOPIC_PRODUCT_UNPUBLISHED:product-unpublished}"
        promotionStarted-out-0:
          destination: "${KAFKA_TOPIC_PROMOTION_STARTED:promotion-started}"
        promotionClosed-out-0:
          destination: "${KAFKA_TOPIC_PROMOTION_CLOSED:promotion-closed}"
      kafka:
        binder:
          brokers: "${KAFKA_BOOTSTRAP_SERVERS:kafka:29092}"
          configuration:
            schema.registry.url: "${SCHEMA_REGISTRY_URL:http://schema-registry:8081}"
            value.serializer: "io.confluent.kafka.serializers.KafkaAvroSerializer"
        bindings:
          articleCreated-out-0:
            producer:
              useNativeEncoding: true
          promotionCreated-out-0:
            producer:
              useNativeEncoding: true
          productPublished-out-0:
            producer:
              useNativeEncoding: true
          productUnpublished-out-0:
            producer:
              useNativeEncoding: true
          promotionStarted-out-0:
            producer:
              useNativeEncoding: true
          promotionClosed-out-0:
            producer:
              useNativeEncoding: true

application:
  promotion:
    batch:
      cron: "0 */5 * * * *"
