spring:
  application:
    name: "${SPRING_APPLICATION_NAME:product}"
  datasource:
    url: "${DB_URL}"
  kafka:
    bootstrap-servers: kafka:29092
    producer:
      key-serializer: "org.apache.kafka.common.serialization.StringSerializer"
      value-serializer: "org.springframework.kafka.support.serializer.JsonSerializer"
      properties:
        acks: "all"
        retries: "3"
    topic:
      product-created: "article-created"
      promotion-created: "promotion-created"

application:
  promotion:
    batch:
      cron: "0 */5 * * * *"