spring:
  application:
    name: "${SPRING_APPLICATION_NAME:stats}"
  cache:
    type: redis
  data:
    redis:
      host: "${REDIS_HOST:redis}"
      port: "${REDIS_PORT:6379}"
  datasource:
    url: "${DB_URL}"
  cloud:
    function:
      definition: articleCreatedConsumer;promotionCreatedConsumer;businessCreatedConsumer
    stream:
      bindings:
        articleCreatedConsumer-in-0:
          destination: "${KAFKA_TOPIC_ARTICLE_CREATED:article-created}"
          group: "${KAFKA_GROUP_ID:stats-service}"
          content-type: "application/json"
        promotionCreatedConsumer-in-0:
          destination: "${KAFKA_TOPIC_PROMOTION_CREATED:promotion-created}"
          group: "${KAFKA_GROUP_ID:stats-service}"
          content-type: "application/json"
        businessCreatedConsumer-in-0:
          destination: "${KAFKA_TOPIC_BUSINESS_CREATED:business-created}"
          group: "${KAFKA_GROUP_ID:stats-service}"
          content-type: "application/json"
      kafka:
        bindings:
          articleCreatedConsumer-in-0:
            consumer:
              start-offset: earliest
              enable-dlq: true
              dlq-name: "${KAFKA_TOPIC_ARTICLE_CREATED:article-created}.dlq"
          promotionCreatedConsumer-in-0:
            consumer:
              start-offset: earliest
              enable-dlq: true
              dlq-name: "${KAFKA_TOPIC_PROMOTION_CREATED:promotion-created}.dlq"
          businessCreatedConsumer-in-0:
            consumer:
              start-offset: earliest
              enable-dlq: true
              dlq-name: "${KAFKA_TOPIC_BUSINESS_CREATED:business-created}.dlq"
