spring:
  application:
    name: "${SPRING_APPLICATION_NAME:subscription}"
  cache:
    type: redis
  data:
    redis:
      host: "${REDIS_HOST:redis}"
      port: "${REDIS_PORT:6379}"
  datasource:
    url: "${DB_URL}"
  cloud:
    function:
      definition: transferRequestCreatedConsumer
    stream:
      bindings:
        transferRequestCreatedConsumer-in-0:
          destination: "${KAFKA_TOPIC_TRANSFER_REQUEST_CREATED:transfer-request-created}"
          group: "${KAFKA_GROUP_SUBSCRIPTION:subscription-service}"
          content-type: "application/json"
        subscriptionCreated-out-0:
          destination: "${KAFKA_TOPIC_SUBSCRIPTION_CREATED:subscription-created}"
          content-type: "application/json"
        subscriptionExpired-out-0:
          destination: "${KAFKA_TOPIC_SUBSCRIPTION_EXPIRED:subscription-expired}"
          content-type: "application/json"

subscription:
  expiration:
    cron: "0 0 0 * * *"
