spring:
  application:
    name: "${SPRING_APPLICATION_NAME:subscription}"
  cache:
    type: redis
  data:
    redis:
      host: "${REDIS_HOST:redis}"
      port: "${REDIS_PORT:6379}"
  datasource:
    url: "${DB_URL}"
  cloud:
    stream:
      bindings:
        subscriptionCreated-out-0:
          destination: "${KAFKA_TOPIC_SUBSCRIPTION_CREATED:subscription-created}"
          content-type: "application/json"
        subscriptionExpired-out-0:
          destination: "${KAFKA_TOPIC_SUBSCRIPTION_EXPIRED:subscription-expired}"
          content-type: "application/json"

subscription:
  expiration:
    cron: "0 0 0 * * *"
