spring:
  application:
    name: "${SPRING_APPLICATION_NAME:usermanager}"
  datasource:
    url: "jdbc:postgresql://postgres_usermanager:5432/db_usermanager"
  kafka:
    bootstrap-servers: kafka:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        # for production
        acks: all
        retries: 3
        batch.size: 16384
        linger.ms: 1
        buffer.memory: 33554432
