spring:
  application:
    name: "${SPRING_APPLICATION_NAME:user}"
  datasource:
    url: "${DB_URL}"
    driver-class-name: "${DB_DRIVER_CLASS_NAME:org.postgresql.Driver}"
  cache:
    type: redis
  data:
    redis:
      host: "${REDIS_HOST:redis}"
      port: "${REDIS_PORT:6379}"
  cloud:
    stream:
      bindings:
        userCreated-out-0:
          destination: "${KAFKA_TOPIC_USER_CREATED:user-created}"
          content-type: "application/*+avro"
      kafka:
        binder:
          configuration:
            schema.registry.url: "${SCHEMA_REGISTRY_URL:http://schema-registry:8081}"
            value.serializer: "io.confluent.kafka.serializers.KafkaAvroSerializer"
        bindings:
          userCreated-out-0:
            producer:
              useNativeEncoding: true
              sync: true
              configuration:
                value.serializer: "io.confluent.kafka.serializers.KafkaAvroSerializer"

server:
  port: "${SERVER_PORT:8083}"
