{
  "type": "record",
  "name": "ArticleCreatedEvent",
  "namespace": "cm.fastrelays.events",
  "fields": [
    { "name": "id", "type": "string", "logicalType": "uuid" },
    { "name": "name", "type": "string" },
    { "name": "quantity", "type": "int" },
    { "name": "description", "type": ["null", "string"], "default": null },
    { "name": "price", "type": "MoneyEvent" },
    { "name": "specifications", "type": ["null", { "type": "map", "values": "string" }], "default": null },
    { "name": "category", "type": ["null", "string"], "default": null },
    { "name": "images", "type": ["null", { "type": "map", "values": "string" }], "default": null },
    { "name": "businessId", "type": "string", "logicalType": "uuid" },
    { "name": "createdBy", "type": "string" },
    { "name": "userId", "type": ["null", "string"], "default": null, "logicalType": "uuid" },
    { "name": "status", "type": "string" },
    { "name": "eventId", "type": "string", "logicalType": "uuid" }
  ]
}
