{
  "type": "record",
  "name": "OrderDeliveredEvent",
  "namespace": "cm.fastrelays.events",
  "fields": [
    { "name": "id", "type": "string", "logicalType": "uuid" },
    { "name": "businessId", "type": "string", "logicalType": "uuid" },
    { "name": "deliveredBy", "type": "string" },
    { "name": "userId", "type": ["null", "string"], "default": null, "logicalType": "uuid" },
    { "name": "deliveredAt", "type": "string", "format": "date-time" },
    { "name": "eventId", "type": "string", "logicalType": "uuid" }
  ]
}
