{
  "type": "record",
  "name": "PromotionClosedEvent",
  "namespace": "cm.fastrelays.events",
  "fields": [
    { "name": "id", "type": "string", "logicalType": "uuid" },
    { "name": "articleId", "type": "string", "logicalType": "uuid" },
    { "name": "businessId", "type": "string", "logicalType": "uuid" },
    { "name": "closedBy", "type": "string" },
    { "name": "discountPercentage", "type": ["null", "string"], "default": null },
    { "name": "userId", "type": ["null", "string"], "default": null, "logicalType": "uuid" },
    { "name": "closedAt", "type": "string", "format": "date-time" },
    { "name": "eventId", "type": "string", "logicalType": "uuid" }
  ]
}
