{
  "type": "record",
  "name": "PromotionCreatedEvent",
  "namespace": "cm.fastrelays.events",
  "fields": [
    { "name": "id", "type": "string", "logicalType": "uuid" },
    { "name": "discountPercentage", "type": "string" },
    { "name": "period", "type": "PeriodEvent" },
    { "name": "articleId", "type": "string", "logicalType": "uuid" },
    { "name": "businessId", "type": "string", "logicalType": "uuid" },
    { "name": "createdBy", "type": "string" },
    { "name": "userId", "type": ["null", "string"], "default": null, "logicalType": "uuid" },
    { "name": "status", "type": "string" },
    { "name": "description", "type": ["null", "string"], "default": null },
    { "name": "productQuantity", "type": ["null", "int"], "default": null },
    { "name": "productSpecifications", "type": ["null", { "type": "map", "values": "string" }], "default": null },
    { "name": "eventId", "type": "string", "logicalType": "uuid" }
  ]
}
