{
  "type": "record",
  "name": "SubscriptionExpiredEvent",
  "namespace": "cm.fastrelays.events",
  "fields": [
    { "name": "id", "type": "string", "logicalType": "uuid" },
    { "name": "businessId", "type": "string", "logicalType": "uuid" },
    { "name": "username", "type": "string" },
    { "name": "userId", "type": ["null", "string"], "default": null, "logicalType": "uuid" },
    { "name": "planId", "type": "string", "logicalType": "uuid" },
    { "name": "expiredAt", "type": "string", "format": "date-time" },
    { "name": "eventId", "type": "string", "logicalType": "uuid" }
  ]
}
